### ISSUE TITLE
Feature Request: Power Off endpoint

### ISSUE THREAD

**Issue by CyborgEric** [sphero-inc/sphero-sdk-raspberrypi-nodejs#4]
Hello!  I just found out RVR supports shutdown commands via the UART port via [here.](https://community.sphero.com/t/power-off-board-rvr/1280/2)  Is there any chance we can receive an update to the power commands to include this functionality?

**Comment by meganrobinson22** [comment]
Hey @BTEric,

We appreciate your request! However, we don't currently have plans to add this command to this or any other public SDK. We deliberately excluded this command from all of our public SDKs since it kills power to the third party hardware, and killing power before properly shutting down can damage some boards.

I can see in the discussion you linked that you and other users have been playing with this command in raw API form, so if you continue to do so just keep in mind that you'll need to add a delay to give your board time to shut down before it loses power!

**Comment by CyborgEric** [comment]
No worries, thanks for the response!
